apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        # Ganti dengan username Docker Hub kamu
        image: sayyidusyalghiffari/order-service:latest 
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: AMQP_URL
          value: "amqp://rabbitmq-service:5672"